### ISSUE TITLE
OOM when benchmarking a gradle task

### ISSUE THREAD

**Issue by maxim-pandra** [gradle/gradle-profiler#156] opened 2019-10-01 13:28 UTC
Some help needed.

I run `gradle-profiler --benchmark --project-r ~/AndroidStudioProjects/android_app/ :AndroidSubModule:assemble` and getting OOM after a couple of measured builds.

Looks like there is a memory leak in my project but I can run the task repeatedly from console, so I am not sure.

I've attached JVM memory allocation chart of projects gradle daemon. The daemon of profiler looks ok. https://imgur.com/a/ajSJF40

Please give me some advice where to look. 
I can use --profile flag but I want to use gradle-profiler for more reliable results.

p.s
project has a lot of modules

**Comment by paplorinc** [comment] 2019-10-01 13:33
Thanks for reporting it Maxim.
Is it possible for you to try it with latest Gradle version?
Latest stable at this point is `5.6.2`, your screenshot seems to indicate `5.5`.

**Comment by oehme** [comment] 2019-10-01 13:35
To detect memory leaks, create a heap dump after you've done a few builds. That'll show you where the objects are being held. The usual culprit are static caches holding `Task` or `Project` instances of previous builds.

Closing as this is not a bug or feature request for the profiler itself.

**Closed by oehme** 2019-10-01 13:35 UTC

**Comment by maxim-pandra** [comment] 2019-10-01 13:37
Thanks!

**Comment by maxim-pandra** [comment] 2019-10-01 14:39
@paplorinc  on gradle 5.6.2 results are the same. First two measured builds are fast. Third is slow due to GC. Forth fails with OOM

**Comment by paplorinc** [comment] 2019-10-01 15:44
As @oehme mentioned, we would need more data to be able to help.
You could do a heap dump and trace it back to the source of the leak.
If you suspect it's a Gradle problem after your investigation, please open an issue, preferably with a reproducer project.
