### ISSUE TITLE
Android studio sync measurement fails in 2nd build

### ISSUE THREAD

**Issue by ghus-raba** [gradle/gradle-profiler#377] opened 2021-11-25 15:19 UTC
We have a scenario file:

```
studio_sync {
    android-studio-sync {
    }
}
```

That we run with following command:

```shell
gradle-profiler --scenario-file scenarios.txt studio_sync --benchmark --studio-install-dir <install_dir>
```

I am running a `gradle-profiler` built from source (at 72fd85694fcd18b49ba2b03cda401787390374b5), as latest binary release (0.16.0) does not support Android Studio 7+ (becuse of https://github.com/gradle/gradle-profiler/pull/358). 

Android Studio version used is Bumblebee 2021.1.1 Beta 4 currently in beta, but latest stable (Arctic Fox) does not work with:

```
Plugin 'Gradle Profiler IntelliJ/Android Studio Plugin' (version '0.17.0-alpha09') is not compatible with the current version of the IDE, because it requires build 211.0 or newer but the current build is AI-203.7717.56
```

More Studio info:

Build #AI-211.7628.21.2111.7905991, built on November 11, 2021
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 16

While the same setup works with smaller project like https://github.com/material-components/material-components-android, when used on our work project, we get following output and Studio stays open doing nothing.

```
* Running sync in Android Studio...
* Sent sync request
* Sync has started, waiting for it to complete...
* Gradle invocation has completed in: 42783ms
* Full sync has completed in: 344462ms and it succeeded
Execution time 344462 ms

* Running warm-up build #2
* Running sync in Android Studio...
* Sent sync request
* Sync has started, waiting for it to complete...
* Stopping Android Studio....
* Android Studio stopped.
```

After manually closing the Studio the process fails with:

```
* Stopping daemons
java.lang.ClassCastException: Cannot cast org.gradle.profiler.client.protocol.messages.GradleInvocationStarted to org.gradle.profiler.client.protocol.messages.GradleInvocationCompleted
	at java.base/java.lang.Class.cast(Class.java:3605)
	at org.gradle.profiler.client.protocol.serialization.MessageProtocolHandler.receive(MessageProtocolHandler.java:42)
	at org.gradle.profiler.client.protocol.ServerConnection.receiveGradleInvocationCompleted(ServerConnection.java:35)
	at org.gradle.profiler.studio.StudioGradleClient.lambda$sync$1(StudioGradleClient.java:83)
	at org.gradle.profiler.studio.process.StudioProcessController.run(StudioProcessController.java:64)
	at org.gradle.profiler.studio.process.StudioProcessController.run(StudioProcessController.java:43)
	at org.gradle.profiler.studio.StudioGradleClient.sync(StudioGradleClient.java:74)
	at org.gradle.profiler.AndroidStudioSyncAction.run(AndroidStudioSyncAction.java:33)
	at org.gradle.profiler.BuildUnderTestInvoker$InvokeAndMeasureAction.run(BuildUnderTestInvoker.java:60)
	at org.gradle.profiler.BuildUnderTestInvoker$InvokeAndMeasureAction.run(BuildUnderTestInvoker.java:41)
	at org.gradle.profiler.RunBuildStepAction.run(RunBuildStepAction.java:29)
	at org.gradle.profiler.ScenarioInvoker.runMeasured(ScenarioInvoker.java:36)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:117)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:21)
	at org.gradle.profiler.ScenarioInvoker.run(ScenarioInvoker.java:17)
	at org.gradle.profiler.Main.invoke(Main.java:117)
	at org.gradle.profiler.Main.run(Main.java:79)
	at org.gradle.profiler.Main.main(Main.java:21)

* Results written to /Users/nagy/EgitProjects/george-app-android/profile-out-3
  /Users/nagy/EgitProjects/george-app-android/profile-out-3/benchmark.csv
  /Users/nagy/EgitProjects/george-app-android/profile-out-3/benchmark.html
```

Here I am attaching full logs from the benchmark run:
[profile.log](https://github.com/gradle/gradle-profiler/files/7603908/profile.log)
[idea.log](https://github.com/gradle/gradle-profiler/files/7603912/idea.log)

Thanks for any help and let me know if I can provide any additional info.

**Comment by asodja** [comment] 2021-11-25 17:09
Yeah, we only support sync with Bumblebee and higher on master. We should add that to the README. 

Since you build it from a source you can try changing the required version here:
https://github.com/gradle/gradle-profiler/blob/72fd85694fcd18b49ba2b03cda401787390374b5/subprojects/studio-plugin/src/main/resources/META-INF/plugin.xml#L10, but I did not test it with that version so I can't say if there is any incompatible API used.

Latest gradle-profiler that supports any version is at: 4b7a01c9a2d1d5d34f1a8b29ad96be0d056eef63. But that one does not do a sync automatically.

**Comment by ghus-raba** [comment] 2021-11-25 17:20
I am fine with running it on Bumblebee. The mention of Arctic Fox is more of a side note, although mentioning the support in readme sounds like a good idea. 

My issue is that on Bumblebee after the first run, the 2nd sync starts, but then the measurement stops unexpectedly.

**Comment by asodja** [comment] 2021-11-25 17:21
Regarding the error, it looks like there is a timeout when waiting for sync parameters. So increasing that value might help:
https://github.com/gradle/gradle-profiler/blob/72fd85694fcd18b49ba2b03cda401787390374b5/subprojects/instrumentation-support/src/main/java/org/gradle/profiler/studio/instrumented/Interceptor.java#L21

It looks like that value was accidentally changed from 300s to 60s. Can you try increase that value and see if that helps with your case?

**Comment by ghus-raba** [comment] 2021-11-26 09:06
Thanks for the suggestion, but it did not help in our case. I tried various values like 30, 300, 600, 3600 seconds, but the result was same. I also tried to use `--studio-sandbox-dir` and `--no-studio-sandbox`, but neither of them helped either.

To shed more light on the project: 
 - the first opening in studio takes about 6.5 minutes to index all the dependencies
 - the first sync took ~1.5min
 - subsequent sync takes ~40s

**Comment by asodja** [comment] 2021-11-26 09:32
Could you maybe share the project, so I can see where the issue is? But yeah, it seems like some timeouts are too strict.

**Comment by ghus-raba** [comment] 2021-11-26 11:06
Unfortunately not, it is our company production code that is not publicly available. If there are some logs that could help identify the pain point, I can try to gather them.

**Comment by asodja** [comment] 2021-11-26 11:06
I think I was able to reproduce it with gradle/gradle. It looks like IntelliJ calls Gradle connector multiple times. Probably because of buildSrc/included builds. I will check how we can solve this.

**Comment by ghus-raba** [comment] 2021-11-26 11:10
Great. I can also confirm, that we do have a `buildSrc` in our project - mostly for defining dependency versions, but also a couple precompiled script plugins.

**Comment by asodja** [comment] 2021-11-29 07:54
@ghus-raba this should be fixed with https://github.com/gradle/gradle-profiler/pull/379. Can you maybe try it with asodja/studio-buildsrc-fix branch?

**Comment by ghus-raba** [comment] 2021-11-29 08:55
I just tried the build from your branch and can confirm that it fixes the issue for our project and the measurement completes succesfully. Thank you for the quick fix. 👍

**Comment by asodja** [comment] 2021-11-29 12:50
Thanks for the bug report and also for verifying it.

**Closed** 2021-11-30 14:24 UTC
Labels: @execution
