### ISSUE TITLE
Cannot move trace file to final destination

### ISSUE THREAD

**Issue by cdsap** [gradle/gradle-profiler#84] opened 2018-09-04 09:26 UTC
Hi, 
thanks for this excellent tool.
I'm having some problems on CI trying to execute the profiling with chrome-trace. 
Locally everything works OK. 
The error I'm having is 
``` 
Caused by: org.gradle.internal.exceptions.LocationAwareException: Failed to notify build listener
Caused by: java.lang.RuntimeException: Failed to move the trace file from a temporary location (/tmp/gradle-trace935783717352237237.html) to the final location (/opt/buildagent/work/8ac15c76182f828b/profile-out/4.5-trace.html)
``` 

If I try manually on CI no problem.
`cp /tmp/gradle-trace935783717352237237.html /opt/buildagent/work/8ac15c76182f828b`

There is something I'm missing?

**Comment by oehme** [comment] 2018-09-05 06:57
I've had the same report from @liutikas, but can't reproduce it myself. I'm not sure why it would fail to copy.

**Comment by wolfs** [comment] 2019-07-31 09:35
@oehme I have the same problem when trying to produce Chrome traces on our CI infrastructure. The reason seems to be that the `/tmp` directory is mounted on `tmpfs`, and it is impossible to move files between file systems.

**Comment by oehme** [comment] 2019-07-31 12:50
I see, so we'd have to fall back to copy in that case?

**Comment by wolfs** [comment] 2019-07-31 12:50
Yeah, I think so.

**Comment by oehme** [comment] 2019-07-31 13:22
Can you give that a shot?

**Comment by wolfs** [comment] 2019-07-31 15:43
Sure, I see when I can find some time.

**Comment by oehme** [comment] 2019-12-06 21:29
Fixed by https://github.com/gradle/gradle-profiler/pull/180

**Closed** 2019-12-06 21:29 UTC
