### ISSUE TITLE
Problem with gradle-4.1

### ISSUE THREAD

**Issue by hazems** [gradle/gradle-profiler#54] opened 2017-12-28 19:00 UTC
I tried to use this tool to profile my android app, and I have the following issue:

```
org.gradle.tooling.BuildException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.1-all.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:77)
	at org.gradle.profiler.GradleVersionInspector.lambda$probe$0(GradleVersionInspector.java:93)
	at org.gradle.profiler.BuildInvoker.run(BuildInvoker.java:48)
	at org.gradle.profiler.GradleVersionInspector.probe(GradleVersionInspector.java:90)
	at org.gradle.profiler.GradleVersionInspector.defaultVersion(GradleVersionInspector.java:66)
	at org.gradle.profiler.ScenarioLoader.adhocScenarios(ScenarioLoader.java:64)
	at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:53)
	at org.gradle.profiler.Main.run(Main.java:52)
	at org.gradle.profiler.Main.main(Main.java:24)
Caused by: org.gradle.internal.exceptions.LocationAwareException: Script 'xxx.gradle' line: 75
A problem occurred evaluating script.
```

Knowing that my app build works fine when doing clean build from gradle cmd line.
I used all of these commands, and none of them work:
1. gradle-profiler --benchmark --project-dir ${my app path} clean build
2. gradle-profiler --profile buildscan --project-dir ${my app path} clean build

Thanks

**Comment by oehme** [comment] 2017-12-28 23:17
Please provide the full stack trace and what line 75 of that script is doing, otherwise there is no way to tell what the problem is.

**Comment by oehme** [comment] 2018-01-14 14:13
Closing since there was not enough information. Feel free to follow up with more details.

**Closed by oehme** 2018-01-14 14:13 UTC
