### ISSUE TITLE
Cannot proceed profile chrome-trace

### ISSUE THREAD

**Issue by Dmitry-Borodin** [gradle/gradle-profiler#89] opened 2018-10-15 13:57 UTC
I have a scenario file with two tasks - clean and build develop

I can run the benchmarks and get the results ./gradle-profiler/build/install/gradle-profiler/bin/gradle-profiler --benchmark --project-dir ./app --scenario-file ./gradle-profiler/perf.scenarios

But when I starting profiling
./gradle-profiler/build/install/gradle-profiler/bin/gradle-profiler --profile chrome-trace --project-dir ./app --scenario-file ./gradle-profiler/perf.scenarios
The first measuring build fails
```
* Running measured build #1 with build tasks [:app:assembleDev]

* What went wrong:
Failed to notify build listener.
> java.lang.reflect.UndeclaredThrowableException (no error message)
> java.lang.reflect.UndeclaredThrowableException (no error message)    

ERROR: failed to run build. See log file for details.
* Stopping daemons
org.gradle.tooling.BuildException: Could not execute build using Gradle installation <...>
<... skipped...>
Caused by: java.lang.RuntimeException: Failed to move the trace file from a temporary location (/tmp/gradle-trace14161318767347713670.html) to the final location (/home/<...>/profile-out/full_build/full_build-4.10.2-trace.html)
	at org.gradle.trace.AsynchronousTraceWriter.finish(AsynchronousTraceWriter.java:53)
	at org.gradle.trace.TraceResult.finalizeTraceFile(TraceResult.java:49)
	at org.gradle.trace.GradleTracingPlugin$TraceFinalizerAdapter.buildFinished(GradleTracingPlugin.java:55)
	... 92 more
```
This file has an access rights -rw------- owned by me, so my user is able to read and write it. I can copy and remove it.

**Comment by oehme** [comment] 2018-10-15 14:13
Duplicate of https://github.com/gradle/gradle-profiler/issues/84. If you have any ideas what might be causing this, your feedback there is welcome.

**Closed by oehme** 2018-10-15 14:13 UTC
